
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: 'Gantt_Build'
  displayName: 'This stage is for building gantt app'
  jobs:
  - job: 'InstallandBuild'
    displayName: Install prerequisites & build app'
    
    steps:
    - script: |
        sudo app-get update
        echo "____D_O_N_E____"
        echo "Y" | sudo apt install npm
        echo "____D_O_N_E____"
        echo "Y" | sudo apt install python3-pip
        echo "____D_O_N_E____"
        echo "Y" | pip3 install -r ./src/data/requirements
      displayName: 'Install prerequisites'