
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: 'Gantt_Build'
  displayName: 'This stage is for building gantt app'
  jobs:
  - job: 'InstallandBuild'
    displayName: Install prerequisites & build app'
    
    steps:
    - script: |
        echo "Y" | sudo apt-get update
        echo "Y" | sudo apt install npm
        echo "Y" | sudo apt install python3-pip
        echo "Y" | sudo apt-get install python3-setuptools
        echo "Y" | pip3 install -r ./src/data/requirements #workin to this moment
        echo "Y" | .src/data/python3 excel.py
      displayName: 'Install prerequisites'