
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: 'Gant Build'
  displayName: 'This stage is for building gantt app'
  jobs:
  - job: 'Install&Build'
    displayName: Install prerequisites & build app'
    
    steps:
    - script: |
        echo "Y" | sudo app-get update
        echo "Y" | sudo apt install npm
        echo "Y" | sudo apt install python3-pip
        echo "Y" | pip3 install -r ./src/data/requirements
      displayName: 'Install prerequisites'